In [12]:
import pandas as pd
from sklearn.model_selection import cross_val_score
df = pd.read_csv("diabetes.csv")
X = df.drop(["Outcome"],1)
y = df["Outcome"]
from sklearn.linear_model import LogisticRegressionCV, LogisticRegression
log_reg = LogisticRegressionCV(random_state=42)
import warnings
warnings.filterwarnings("ignore")
log_reg.fit(X,y)
log_reg.score(X,y)

0.7838541666666666

In [26]:
import numpy as np
features= list(X)
ranking = np.abs(log_reg.coef_.tolist()[0])
d = dict(zip(features,ranking))
d = pd.DataFrame(list(d.items()),columns=["features", "importance"])
d = d.sort_values(["importance"], ascending=False)

In [28]:
log_reg.score(X,y)

0.7838541666666666

In [34]:
X_new = X[["DiabetesPedigreeFunction", "Pregnancies"]]

In [35]:
log_reg.fit(X_new,y)
log_reg.score(X_new,y)

0.6809895833333334

In [38]:
import statsmodels.api as sm

In [40]:
X_sm = sm.add_constant(X)
model = sm.Logit(y,X_sm).fit()


Optimization terminated successfully.
         Current function value: 0.470993
         Iterations 6


In [46]:
drop = list(X_sm)

In [56]:
drop.remove("Age")

In [57]:
drop

['const',
 'Pregnancies',
 'Glucose',
 'BloodPressure',
 'BMI',
 'DiabetesPedigreeFunction']

In [58]:
X_new = X_sm[drop]
model = sm.Logit(y,X_new).fit()
model.summary()

Optimization terminated successfully.
         Current function value: 0.474323
         Iterations 6


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                Outcome   No. Observations:                  768
Model:                          Logit   Df Residuals:                      762
Method:                           MLE   Df Model:                            5
Date:                Sat, 23 Nov 2019   Pseudo R-squ.:                  0.2667
Time:                        16:01:44   Log-Likelihood:                -364.28
converged:                       True   LL-Null:                       -496.74
Covariance Type:            nonrobust   LLR p-value:                 3.442e-55
============================================================================================
                               coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------
const                       -7.9550      0.676    -11.771      0.000      -9.280      -6.630
Pregnancies                  0.1535      0.028      5.514      0.000       0.099       0.208
Glucose                      0.0347      0.003     10.213      0.000       0.028       0.041
BloodPressure               -0.0120      0.005     -2.387      0.017      -0.022      -0.002
BMI                          0.0848      0.014      6.006      0.000       0.057       0.113
DiabetesPedigreeFunction     0.9106      0.294      3.097      0.002       0.334       1.487
============================================================================================
"""

In [60]:
f2 = ["Pregnancies", "Glucose", "BMI", "DiabetesPedigreeFunction"]

In [63]:
from sklearn.feature_selection import RFECV, RFE

In [62]:
log_reg = LogisticRegression()
rfe_cv = RFECV(estimator=log_reg, cv=10)

TypeError: __init__() missing 1 required positional argument: 'estimator'

In [66]:
rfe = RFE(estimator=log_reg, n_features_to_select=4)

In [67]:
rfe.fit(X,y)

RFE(estimator=LogisticRegressionCV(Cs=10, class_weight=None, cv='warn',
                                   dual=False, fit_intercept=True,
                                   intercept_scaling=1.0, l1_ratios=None,
                                   max_iter=100, multi_class='warn',
                                   n_jobs=None, penalty='l2', random_state=42,
                                   refit=True, scoring=None, solver='lbfgs',
                                   tol=0.0001, verbose=0),
    n_features_to_select=4, step=1, verbose=0)

In [68]:
rfe.ranking_

array([1, 1, 3, 5, 4, 1, 1, 2])

In [70]:
rfe.support_

array([ True,  True, False, False, False,  True,  True, False])

In [71]:
print (list(X))

['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age']


In [72]:
f2 = ["Pregnancies", "Glucose", "BMI", "DiabetesPedigreeFunction"]

In [75]:
X = X[f2]

In [80]:
from sklearn.model_selection import train_test_split as tts, GridSearchCV
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
log_reg = LogisticRegression(random_state=42)
X_train, X_test, y_train, y_test = tts(X,y,test_size = 0.25, random_state = 42)
model = log_reg.fit(X_train,y_train)
y_pred = model.predict(X_test)
accuracy_score(y_test,y_pred)

0.75

In [79]:
print (classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.78      0.85      0.81       123
           1       0.68      0.58      0.63        69

    accuracy                           0.75       192
   macro avg       0.73      0.71      0.72       192
weighted avg       0.74      0.75      0.75       192



In [81]:
print (confusion_matrix(y_test,y_pred))

[[104  19]
 [ 29  40]]


In [82]:
144/192

0.75