In [20]:
import pandas as pd

In [21]:
df = pd.read_csv("gapminder.csv")

In [22]:
df.head()

population  fertility  HIV        CO2  BMI_male    GDP  BMI_female  life  \
0    34811059       2.73  0.1   3.328945  24.59620  12314    129.9049  75.3   
1    19842251       6.43  2.0   1.474353  22.25083   7103    130.1247  58.3   
2    40381860       2.24  0.5   4.785170  27.50170  14646    118.8915  75.5   
3     2975029       1.40  0.1   1.804106  25.35542   7383    132.8108  72.5   
4    21370348       1.96  0.1  18.016313  27.56373  41312    117.3755  81.5   

   child_mortality                      Region  
0             29.5  Middle East & North Africa  
1            192.0          Sub-Saharan Africa  
2             15.4                     America  
3             20.0       Europe & Central Asia  
4              5.2         East Asia & Pacific

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 139 entries, 0 to 138
Data columns (total 10 columns):
population         139 non-null int64
fertility          139 non-null float64
HIV                139 non-null float64
CO2                139 non-null float64
BMI_male           139 non-null float64
GDP                139 non-null int64
BMI_female         139 non-null float64
life               139 non-null float64
child_mortality    139 non-null float64
Region             139 non-null object
dtypes: float64(7), int64(2), object(1)
memory usage: 10.9+ KB


In [24]:
X = df.drop(["Region"],1)
y = df["Region"]

In [25]:
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor

In [26]:
dtc = DecisionTreeClassifier()

In [27]:
dtc

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [28]:
from sklearn.model_selection import train_test_split as tts, GridSearchCV, RandomizedSearchCV

In [29]:
X_train, X_test, y_train, y_test = tts(X,y,random_state = 42, test_size = 0.25)

In [30]:
dtc = DecisionTreeClassifier(random_state=42)

In [31]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [32]:
dtc.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=42,
            splitter='best')

In [33]:
#Accuracy score
dtc.score(X_test,y_test)

0.7714285714285715

In [34]:
y_pred = dtc.predict(X_test)

In [35]:
print (classification_report(y_test,y_pred))

                            precision    recall  f1-score   support

                   America       0.80      1.00      0.89         4
       East Asia & Pacific       0.25      0.50      0.33         2
     Europe & Central Asia       0.76      0.93      0.84        14
Middle East & North Africa       0.00      0.00      0.00         4
                South Asia       0.00      0.00      0.00         1
        Sub-Saharan Africa       1.00      0.90      0.95        10

                 micro avg       0.77      0.77      0.77        35
                 macro avg       0.47      0.55      0.50        35
              weighted avg       0.70      0.77      0.73        35



/home/nbuser/anaconda3_501/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [36]:
y.value_counts()

Europe & Central Asia         41
Sub-Saharan Africa            40
America                       27
East Asia & Pacific           14
Middle East & North Africa    10
South Asia                     7
Name: Region, dtype: int64

In [37]:
print (confusion_matrix(y_test,y_pred))

[[ 4  0  0  0  0  0]
 [ 0  1  1  0  0  0]
 [ 0  1 13  0  0  0]
 [ 1  0  3  0  0  0]
 [ 0  1  0  0  0  0]
 [ 0  1  0  0  0  9]]


In [38]:
list(X)

['population',
 'fertility',
 'HIV',
 'CO2',
 'BMI_male',
 'GDP',
 'BMI_female',
 'life',
 'child_mortality']

In [39]:
dtc.feature_importances_

array([0.03832688, 0.36887615, 0.03050507, 0.        , 0.14649508,
       0.03959793, 0.1432666 , 0.09141319, 0.14151909])

In [40]:
dtc = DecisionTreeClassifier(random_state=42, criterion="entropy", max_depth=10, min_samples_split=0.06,class_weight="balanced")

In [41]:
dtc.fit(X_train,X_test)
y_pred_proba = dtc.predict_proba(X_test)

NotFittedError: This DecisionTreeClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.

In [39]:
X_test

population  fertility    HIV        CO2  BMI_male     GDP  BMI_female  \
135    26952719       2.46   0.10   4.476669  25.32054    3733    124.3462   
66     15915966       2.51   0.10  14.718104  26.29078   18797    128.8517   
31      4344151       1.43   0.06   5.287903  26.59629   21873    130.3921   
118    34470138       4.79   1.00   0.382118  22.40484    3246    129.7199   
42      5314170       1.85   0.10  10.644114  26.73339   42122    126.5645   
12       306165       2.91   2.40   1.360126  27.02255    8293    120.9224   
51     10427356       5.34   1.40   0.126964  22.52449    1230    132.2765   
68      2144215       1.50   0.60   3.341849  26.45693   20977    129.5746   
126     6052937       4.88   3.20   0.251983  21.87875    1219    131.0248   
55      7259470       3.27   0.80   1.187454  25.10872    4391    122.9621   
112     5396710       1.31   0.06   6.901654  26.92717   24670    129.5280   
130    31014427       6.34   6.40   0.100853  22.35833    1437    134.5204   
80      3414552       4.94   0.70   0.613104  22.62295    3356    129.9875   
19     14709011       6.04   1.20   0.109419  21.27157    1358    130.6651   
86     22994867       5.54  11.40   0.104748  21.93536     864    135.3949   
69      4109389       1.57   0.10   3.996722  27.20117   14158    127.5037   
11     10779155       1.82   0.20   9.797337  26.75915   41641    121.8227   
27       665414       5.05   0.06   0.178853  22.06131    1440    132.1354   
134     3350832       2.11   0.50   2.489764  26.39123   15317    124.2604   
109     9109535       1.41   0.10   5.271223  26.51495   12522    130.3755   
36     78976122       2.95   0.06   2.512394  26.73243    9974    125.0931   
117    19949553       2.32   0.06   0.580791  21.96671    6907    124.8615   
78     14223403       6.82   1.00   0.041079  21.78881    1602    128.0308   
4      21370348       1.96   0.10  18.016313  27.56373   41312    117.3755   
73       485079       1.63   0.30  22.168080  27.43404   95001    122.3705   
26     44901660       2.43   0.50   1.476092  24.94041   10489    124.0235   
132    61689620       1.87   0.20   8.526467  27.39249   37739    124.0845   
60     72530693       1.88   0.20   7.892211  25.31003   15955    125.1859   
16      1967866       2.86  24.90   2.547205  22.12984   13858    133.1307   
18      7513646       1.43   0.10   6.690139  26.54286   15368    128.4721   
10      9526453       1.42   0.20   6.488174  26.16443   14488    129.7968   
56     10050699       1.33   0.06   5.453232  27.11568   23334    128.6968   
104     1388962       2.20   0.06  48.702062  28.13138  126076    126.3153   
65    127317900       1.34   0.06   9.536606  23.50004   34800    121.9651   
105    20741669       1.34   0.10   4.383449  25.41069   18032    128.7553   

     life  child_mortality  
135  68.7             49.2  
66   66.1             25.9  
31   76.5              5.9  
118  67.4             84.7  
42   79.4              3.3  
12   70.7             20.1  
51   58.3            121.0  
68   72.3             10.5  
126  60.0             96.4  
55   70.9             26.5  
112  74.8              8.8  
130  57.2             89.3  
80   63.6            103.0  
19   59.4            130.4  
86   55.0            114.4  
69   77.6             11.3  
11   79.4              4.7  
27   62.6             91.2  
134  76.0             13.0  
109  76.4              8.0  
36   70.1             31.4  
117  74.3             11.7  
78   55.8            148.3  
4    81.5              5.2  
73   80.7              2.8  
26   75.1             19.7  
132  79.5              5.6  
60   76.9             21.4  
16   61.2             63.8  
18   73.2             13.7  
10   70.1              7.2  
56   73.8              7.2  
104  80.4              9.5  
65   82.6              3.4  
105  73.4             16.1

In [41]:
y_pred_proba

array([[1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.45      , 0.1       , 0.45      , 0.        ,
        0.        ],
       [0.        , 0.        , 1.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        ],
       [0.        , 0.        , 1.        , 0.        , 0.        ,
        0.        ],
       [1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        ],
       [0.        , 0.        , 1.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        ],
       [1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 1.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0

In [42]:
df = pd.read_csv("gapminder (1).csv")

In [48]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X = df.drop(["life"],1)
y = df["life"]
X["Region"] = le.fit_transform(X["Region"])
X_train, X_test, y_train, y_test = tts(X,y,random_state = 42, test_size = 0.25)

In [78]:
dtr = DecisionTreeRegressor(random_state=42, max_depth=4, min_samples_split=0.12, criterion="friedman_mse")

In [79]:
dtr

DecisionTreeRegressor(criterion='friedman_mse', max_depth=4,
           max_features=None, max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=0.12,
           min_weight_fraction_leaf=0.0, presort=False, random_state=42,
           splitter='best')

In [80]:
dtr.fit(X_train,y_train)
dtr.score(X_test,y_test)

0.802932134506581

In [81]:
print (list(X))

['population', 'fertility', 'HIV', 'CO2', 'BMI_male', 'GDP', 'BMI_female', 'child_mortality', 'Region']


In [82]:
dtr.feature_importances_

array([0.00693171, 0.        , 0.06093169, 0.00102591, 0.        ,
       0.01127123, 0.00925062, 0.91058884, 0.        ])

In [83]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np


In [84]:
y_pred = dtr.predict(X_test)

In [85]:
r2_score(y_test,y_pred)

0.802932134506581

In [86]:
mean_squared_error(y_test,y_pred)

12.527152159863968